#!/bin/bash

print_status () {
    status=$1
    if [ -n "$status" ]; then
        printf '%*s%s\n' $(($(tput cols) - ${#status})) " " "$status"
    fi
}


# Low-key wrapped display (and put it back afterwards)
# echo -e "\e[2m----"
# trap 'echo -e "----\e[0m"' EXIT

# git
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHEDSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM="auto verbose name"
GIT_PS1_DESCRIBE_STYLE=branch
GIT_PS1_SHOWCOLORHINTS=1
source ~/src/git/contrib/completion/git-prompt.sh

git=$(__git_ps1)
print_status "$git"

# kubectl
ctx=$(kubectl config current-context)
if [ -n "$ctx" ]; then
    ns=$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"$ctx\")].context.namespace}") || default
    print_status "$ctx / $ns"
fi
